### PR TITLE
Update dark-matter / dark-matter nolabels to have better legibility

### PR DESCRIPTION
**Pull request by VictorVelarde**
Exactly same changes proposed at #25, but updating current dark-matter version (instead of creating a new variation, dark-matter-v2).

Once deployed, it will update vector map for all clients, without any specific action

[sc-192792]

CURRENT
image

NEW
image

Closes #25

### CODE REVIEW

**Comment by VictorVelarde** [comment]
I've tested it a bit, locally, in Data Explorer, and styles look good to me @ernesmb. Once you approve it, I'll talk to infra for deployment

**Comment by VictorVelarde** [comment]
@ernesmb changes also done at nolabels. You can verify results loading these urls in maputnik:

- nolabels: https://raw.githubusercontent.com/CartoDB/basemap-styles/9c46f898b32a3559d475ef15eef6703f938df6ae/mapboxgl/dark-matter-nolabels.json

**Comment by VictorVelarde** [comment]
Once you approve changes @ernesmb, I'll coordinate with @jvillarf for deployment

**Comment by jvillarf** [comment]
https://app.shortcut.com/cartoteam/story/246204

**Comment by VictorVelarde** [comment]
@ernesmb gave me confirmation, so I'll merge

**Pull request merged**
